### PR TITLE
Change button texts that feel a little clunky.

### PR DESCRIPTION
**Pull request by hsychla**

### CODE REVIEW

**Comment by lnikell** [comment]
@hsychla do you mean that those texts are grammatically incorrect?

**Comment by hsychla** [comment]
@lnikell I think so. I am not a native english speaker but claim to have a good feeling for it.

At latest, when there is more than one file, the "a" in the text becomes wrong. 

You can say "Open a file".
You can also say "Open file".
So for a single file, both versions are correct. 

But, you would not say "Open a files" while "Open files" is ok.
So for more than one file the old version is not correct but the new version is.

**Comment by lnikell** [comment]
@hsychla Thanks! I'm mostly curious in case that we use "Open a File(s)" so it's singular + (plural), so not sure should we focus on the plural version or singular from grammar perspective in that case:)

**Comment by hsychla** [comment]
@lnikell That's the thing: I don't think that "Open a File(s)" is singular and plural because it expands to "Open a file" +  "Open a files". The second case doesn't sound right. 

"Open file(s)", on the other hand expands to "Open file" + "Open files". Both sound right, imho.

**Comment by lnikell** [comment]
it makes sense, thank you for clarfication @hsychla

**Pull request merged**
